name: Go

on:
  push:
    branches: [ branch-1.x ]
  pull_request:
    branches: [ branch-1.x ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build
      run: go build -v ./...

    - name: Test
      run: mkdir -p data/test && go test -v ./...
